import React from 'react';
import { ExportFile, BillOfQuantities, GeoLocation } from '../types';
import { FileText, Download, Database, DraftingCompass, Table, Globe } from 'lucide-react';
import * as XLSX from 'xlsx';

interface ExportSectionProps {
  files: ExportFile[];
  billOfQuantities?: BillOfQuantities;
  projectTitle?: string;
  geoLocation?: GeoLocation | null;
}

const ExportSection: React.FC<ExportSectionProps> = ({ files, billOfQuantities, projectTitle, geoLocation }) => {
  
  const handleDownload = (file: ExportFile) => {
    const blob = new Blob([file.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExcelExport = () => {
    const wb = XLSX.utils.book_new();
    const safeTitle = projectTitle || "Engineering_Project";

    // 1. Create Summary Sheet
    const summaryData = [
      ["Project Title", safeTitle],
      ["Date Generated", new Date().toLocaleString()],
      ["Generated By", "EngiVibe 2.5 Pro"],
      [],
      ["Bill of Quantities Summary"],
      ["Total Concrete (m3)", billOfQuantities?.summary.totalConcreteVolume || 0],
      ["Total Steel (kg)", billOfQuantities?.summary.totalSteelWeight || 0],
      ["Total Formwork (m2)", billOfQuantities?.summary.totalFormworkArea || 0],
    ];

    if (geoLocation) {
        summaryData.push([]);
        summaryData.push(["Geo-Location", geoLocation.locationName || "Defined"]);
        summaryData.push(["Latitude", geoLocation.lat]);
        summaryData.push(["Longitude", geoLocation.lng]);
    }

    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

    // 2. Create BoQ Sheet
    if (billOfQuantities?.items) {
      const boqHeaders = ["Item Code", "Description", "Unit", "Quantity", "Remarks"];
      const boqRows = billOfQuantities.items.map(item => [
        item.itemCode,
        item.description,
        item.unit,
        item.quantity,
        item.remarks || ""
      ]);
      const wsBoQ = XLSX.utils.aoa_to_sheet([boqHeaders, ...boqRows]);
      XLSX.utils.book_append_sheet(wb, wsBoQ, "Bill of Quantities");
    }

    // 3. Create Sheets for CSV Files (Stations, Coordinates, etc.)
    files.forEach(file => {
      if (file.type === 'csv' || file.name.endsWith('.csv')) {
        // Simple CSV parser
        const rows = file.content.trim().split('\n').map(row => row.split(',').map(cell => cell.trim()));
        const wsData = XLSX.utils.aoa_to_sheet(rows);
        // Sheet name max length 31 chars
        const sheetName = file.name.replace('.csv', '').substring(0, 30);
        XLSX.utils.book_append_sheet(wb, wsData, sheetName);
      }
    });

    // Write file
    XLSX.writeFile(wb, `${safeTitle.replace(/\s+/g, '_')}_Master_Data.xlsx`);
  };

  const handleKMLExport = () => {
    if (!geoLocation) return;
    const safeTitle = projectTitle || "Project";
    const kmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Placemark>
    <name>${safeTitle}</name>
    <description>Generated by EngiVibe 2.5 Pro</description>
    <Point>
      <coordinates>${geoLocation.lng},${geoLocation.lat},0</coordinates>
    </Point>
  </Placemark>
</kml>`;
    
    const blob = new Blob([kmlContent], { type: 'application/vnd.google-earth.kml+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${safeTitle.replace(/\s+/g, '_')}.kml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getIcon = (type: string) => {
    switch (type) {
      case 'dxf': return <DraftingCompass size={16} />;
      case 's2k': return <Database size={16} />;
      default: return <FileText size={16} />;
    }
  };

  const dxfFile = files.find(f => f.type === 'dxf' || f.name.endsWith('.dxf'));
  const otherFiles = files.filter(f => f !== dxfFile);

  if (files.length === 0 && !billOfQuantities && !geoLocation) return null;

  return (
    <div className="space-y-3">
       <div className="font-mono text-xs text-cyan-500 mb-2 border-b border-cyan-500/30 pb-1">
        // EXPORT_MANIFEST
      </div>

      {/* Primary: AutoCAD DXF Export */}
      {dxfFile && (
        <button 
            onClick={() => handleDownload(dxfFile)}
            className="w-full flex items-center justify-between p-3 bg-orange-900/30 border border-orange-800/50 rounded-lg group hover:bg-orange-900/50 hover:border-orange-500/50 transition-all mb-2 shadow-lg"
        >
            <div className="flex items-center gap-3">
                <div className="p-2 bg-orange-900/80 rounded text-orange-300 shadow-inner border border-orange-700">
                    <DraftingCompass size={20} />
                </div>
                <div className="flex flex-col items-start">
                    <span className="text-sm font-bold text-orange-100 group-hover:text-white transition-colors">AutoCAD 2D (.DXF)</span>
                    <span className="text-[10px] text-orange-400/80">Drafting Commands & Layers</span>
                </div>
            </div>
            <div className="p-1.5 bg-orange-950/50 rounded group-hover:bg-orange-600 transition-colors text-orange-400 group-hover:text-white">
                <Download size={18} />
            </div>
        </button>
      )}

      {/* Primary: Master Excel Button */}
      <button 
        onClick={handleExcelExport}
        className="w-full flex items-center justify-between p-3 bg-green-900/30 border border-green-800/50 rounded-lg group hover:bg-green-900/50 hover:border-green-500/50 transition-all mb-2"
      >
        <div className="flex items-center gap-3">
            <div className="p-2 bg-green-900/80 rounded text-green-300 shadow-lg">
                <Table size={18} />
            </div>
            <div className="flex flex-col items-start">
                <span className="text-sm font-bold text-green-100">Master Project Excel</span>
                <span className="text-[10px] text-green-400/80">Includes BoQ & Coordinate Tables</span>
            </div>
        </div>
        <Download size={18} className="text-green-400 group-hover:text-green-200" />
      </button>

      {/* Primary: Google Earth KML Button */}
      {geoLocation && (
          <button 
            onClick={handleKMLExport}
            className="w-full flex items-center justify-between p-3 bg-blue-900/30 border border-blue-800/50 rounded-lg group hover:bg-blue-900/50 hover:border-blue-500/50 transition-all mb-4"
          >
            <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-900/80 rounded text-blue-300 shadow-lg">
                    <Globe size={18} />
                </div>
                <div className="flex flex-col items-start">
                    <span className="text-sm font-bold text-blue-100">Google Earth (.KML)</span>
                    <span className="text-[10px] text-blue-400/80">View {geoLocation.lat.toFixed(4)}, {geoLocation.lng.toFixed(4)}</span>
                </div>
            </div>
            <Download size={18} className="text-blue-400 group-hover:text-blue-200" />
          </button>
      )}

      {/* Secondary Files */}
      {otherFiles.map((file, idx) => (
        <div 
          key={idx} 
          className="flex items-center justify-between p-3 bg-slate-800 border border-slate-700 rounded-lg group hover:border-cyan-500/50 transition-all"
        >
          <div className="flex items-center gap-3 overflow-hidden">
            <div className="p-2 bg-slate-900 rounded text-cyan-400">
              {getIcon(file.type)}
            </div>
            <div className="flex flex-col min-w-0">
              <span className="text-sm font-medium text-slate-200 truncate">{file.name}</span>
              <span className="text-xs text-slate-500 truncate">{file.description}</span>
            </div>
          </div>
          <button 
            onClick={() => handleDownload(file)}
            className="ml-2 p-2 text-slate-400 hover:text-white hover:bg-slate-700 rounded transition-colors"
            title="Download File"
          >
            <Download size={18} />
          </button>
        </div>
      ))}
    </div>
  );
};

export default ExportSection;