import React, { useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { FileDown, Printer, ShieldCheck } from 'lucide-react';

interface ReportPanelProps {
  markdown: string | null;
  projectTitle?: string;
  onRunAudit: () => void;
  isAuditing?: boolean;
}

// Define components outside of the render function to prevent re-creation on every render
const MarkdownComponents = {
  h1: ({node, ...props}: any) => <h1 className="text-xl font-bold text-slate-100 mt-4 mb-2" {...props} />,
  h2: ({node, ...props}: any) => <h2 className="text-lg font-semibold text-cyan-400 mt-4 mb-2 uppercase tracking-wide" {...props} />,
  h3: ({node, ...props}: any) => <h3 className="text-md font-medium text-slate-200 mt-3 mb-1" {...props} />,
  p: ({node, ...props}: any) => <p className="text-slate-300 mb-3 leading-relaxed" {...props} />,
  ul: ({node, ...props}: any) => <ul className="list-disc list-inside text-slate-300 mb-4" {...props} />,
  li: ({node, ...props}: any) => <li className="mb-1" {...props} />,
  table: ({node, ...props}: any) => <div className="overflow-x-auto my-4 border border-slate-700 rounded"><table className="min-w-full divide-y divide-slate-700" {...props} /></div>,
  thead: ({node, ...props}: any) => <thead className="bg-slate-800" {...props} />,
  th: ({node, ...props}: any) => <th className="px-3 py-2 text-left text-xs font-medium text-slate-300 uppercase tracking-wider" {...props} />,
  td: ({node, ...props}: any) => <td className="px-3 py-2 whitespace-nowrap text-sm text-slate-400 border-t border-slate-700" {...props} />,
  code: ({node, ...props}: any) => <code className="bg-slate-800 px-1 py-0.5 rounded text-yellow-500 font-mono text-xs" {...props} />,
};

const ReportPanel: React.FC<ReportPanelProps> = ({ markdown, projectTitle, onRunAudit, isAuditing }) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleExportPDF = () => {
    const content = contentRef.current;
    if (!content) return;

    // Create a virtual window for printing
    const printWindow = window.open('', '', 'width=900,height=800');
    if (!printWindow) return;

    const dateStr = new Date().toLocaleDateString('en-US', { 
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' 
    });

    // Write the full HTML document for the PDF/Print view
    printWindow.document.write(`
      <html>
        <head>
          <title>${projectTitle || 'Technical Report'}</title>
          <style>
            @page { margin: 2.5cm; }
            body { 
              font-family: 'Helvetica', 'Arial', sans-serif; 
              color: #000; 
              line-height: 1.5; 
              font-size: 11pt;
            }
            .report-header {
              border-bottom: 2px solid #000;
              padding-bottom: 10px;
              margin-bottom: 30px;
            }
            .report-title {
              font-size: 18pt;
              font-weight: bold;
              margin: 0;
              text-transform: uppercase;
            }
            .meta-info {
              margin-top: 10px;
              font-family: 'Courier New', monospace;
              font-size: 9pt;
              color: #444;
            }
            h1, h2, h3 { color: #000; margin-top: 20px; margin-bottom: 10px; }
            h1 { font-size: 16pt; border-bottom: 1px solid #ccc; }
            h2 { font-size: 14pt; background-color: #f0f0f0; padding: 5px; }
            h3 { font-size: 12pt; font-weight: bold; text-decoration: underline; }
            table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 10pt; }
            th, td { border: 1px solid #000; padding: 6px; text-align: left; }
            th { background-color: #e0e0e0; font-weight: bold; }
            ul { margin-bottom: 15px; }
            code { background-color: #eee; padding: 2px 4px; font-family: 'Courier New', monospace; }
          </style>
        </head>
        <body>
          <div class="report-header">
            <h1 class="report-title">${projectTitle || 'ENGINEERING TECHNICAL REPORT'}</h1>
            <div class="meta-info">
              <p>GENERATED BY: EngiVibe 2.5 Pro (Powered by Gemini 3)</p>
              <p>DATE: ${dateStr}</p>
              <p>PROJECT ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
            </div>
          </div>
          <div class="content">
            ${content.innerHTML}
          </div>
          <script>
            window.onload = function() { window.print(); window.close(); }
          </script>
        </body>
      </html>
    `);
    
    printWindow.document.close();
  };

  if (!markdown) {
    return (
      <div className="flex items-center justify-center h-full text-slate-500 font-mono text-sm italic">
        Generate a design to view the technical report.
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col relative">
      {/* Header with Actions */}
      <div className="flex justify-between items-center mb-2 pb-2 border-b border-cyan-500/30 shrink-0">
        <div className="font-mono text-xs text-cyan-500">
          // TECHNICAL_REPORT.MD
        </div>
        <div className="flex gap-2">
            <button 
                onClick={onRunAudit}
                disabled={isAuditing}
                className={`flex items-center gap-1.5 px-2 py-1 text-xs rounded transition-colors border ${
                    isAuditing 
                    ? 'bg-orange-900/40 text-orange-300 border-orange-800 cursor-wait' 
                    : 'bg-slate-800 hover:bg-slate-700 text-slate-300 border-slate-700 hover:text-white'
                }`}
                title="Run AI Code Audit"
            >
                <ShieldCheck size={12} className={isAuditing ? 'animate-pulse' : ''} />
                <span>{isAuditing ? 'AUDITING...' : 'AUDIT'}</span>
            </button>
            <button 
                onClick={handleExportPDF}
                className="flex items-center gap-1.5 px-2 py-1 bg-cyan-900/40 hover:bg-cyan-900/80 text-cyan-300 text-xs rounded transition-colors border border-cyan-800"
                title="Export as PDF"
            >
                <Printer size={12} />
                <span>PDF</span>
            </button>
        </div>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto pr-2 prose prose-invert prose-sm max-w-none custom-scrollbar">
        {/* Hidden ref source for printing - we render markdown here for display */}
        <div ref={contentRef}>
          <ReactMarkdown components={MarkdownComponents}>
            {markdown}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
};

export default ReportPanel;